name: ShopConverter
author: Tanner Embry (SnowGears)
description: Convert ChestShop shops into Shop shops.
version: 1.0
main: com.snowgears.shopconverter.ShopConverter
depend: [ChestShop, Shop]
commands:
   shopconvert:
      description: Different commands pertaining to plugin
      usage: /<command>